nome = input ('Digite seu nome: ')
idade = input ('Digite sua idade: ')
mes = input ('Digite seu mês de nascimento: ')
peso = input ('Digite seu peso: ')
cidade = input ('Digite sua cidade: ')
emprego = input ('Digite seu emprego: ')
print ('Seu nome é', nome, 'você tem', idade, 'anos, nasceu em', mes, ', tem o peso de', peso, 'kg, mora na cidade de', cidade, 'e trabalha como', emprego)
